packages:
  - "front-end"
  - "back-end/*"
  - "back-end/libs/*"

allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  unrs-resolver: true

ignoredOptionalDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

injectWorkspacePackages: true
