export const SERVICE_A_RMQ_CLIENT = 'SERVICE_A_RMQ_CLIENT';
export const SERVICE_A_IMPORTS_RMQ_CLIENT = 'SERVICE_A_IMPORTS_RMQ_CLIENT';
export const SERVICE_B_RMQ_CLIENT = 'SERVICE_B_RMQ_CLIENT';
export const RABBITMQ_CONNECTION_MANAGER = 'RABBITMQ_CONNECTION_MANAGER';
